# Generated by Django 2.0.5 on 2019-01-15 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('unique_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('google_results', models.TextField(blank=True)),
                ('site_data', models.TextField(blank=True)),
            ],
        ),
    ]
